[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "scPOLY doc demo"
authors = [{name = "FirstName LastName", email = "xxx@geemail[dot]commm"}]
dynamic = ["version", "description"]
